"""
Framework implementations for Attestful.

Provides framework-specific logic for NIST CSF 2.0, NIST 800-53,
FedRAMP, SOC 2, ISO 27001, and HITRUST.
"""

from attestful.frameworks.soc2 import (
    SOC2_CONTROLS,
    SOC2_FRAMEWORK_ID,
    SOC2_VERSION,
    SOC2Control,
    SOC2Framework,
    TSC_AVAILABILITY,
    TSC_CONFIDENTIALITY,
    TSC_PRIVACY,
    TSC_PROCESSING_INTEGRITY,
    TSC_SECURITY,
    create_soc2_evaluator,
    get_soc2_aws_checks,
    get_soc2_azure_checks,
    get_soc2_gcp_checks,
    get_soc2_framework,
)
from attestful.frameworks.nist_800_53 import (
    NIST_800_53_CONTROLS,
    NIST_800_53_FRAMEWORK_ID,
    NIST_800_53_VERSION,
    NIST80053Control,
    NIST80053Framework,
    FEDRAMP_LOW,
    FEDRAMP_MODERATE,
    FEDRAMP_HIGH,
    create_nist_800_53_evaluator,
    get_nist_800_53_aws_checks,
    get_nist_800_53_framework,
    get_fedramp_baseline_controls,
)
from attestful.frameworks.iso_27001 import (
    ISO_27001_CONTROLS,
    ISO_27001_FRAMEWORK_ID,
    ISO_27001_VERSION,
    ISO27001Control,
    ISO27001Framework,
    DOMAIN_ORGANIZATIONAL,
    DOMAIN_PEOPLE,
    DOMAIN_PHYSICAL,
    DOMAIN_TECHNOLOGICAL,
    create_iso_27001_evaluator,
    get_iso_27001_aws_checks,
    get_iso_27001_framework,
    get_controls_by_domain,
    get_control_count_by_domain,
)
from attestful.frameworks.nist import (
    # Control definitions
    MaturityCriteria,
    NistCategory,
    NistFunction,
    NistSubcategory,
    get_all_categories,
    get_all_functions,
    get_all_subcategories,
    get_category,
    get_function,
    get_subcategory,
    # Mapping engine
    ControlMappingResult,
    EvidenceMapping,
    MappingEngine,
    MappingLogic,
    MappingStatus,
    # Maturity calculator
    EntityType,
    MaturityBreakdown,
    MaturityCalculator as NistCSFMaturityCalculator,
    MaturityConfig,
    MaturityScore as NistCSFMaturityScore,
    # OSCAL Converter
    NistCSF2OSCALConverter,
    NistCSF2ProfileGenerator,
    create_nist_csf2_catalog,
    create_nist_csf2_profile,
    ensure_csf2_catalog_exists,
    ensure_csf2_profiles_exist,
    get_csf2_catalog_path,
    get_csf2_profile_path,
    save_nist_csf2_catalog,
    save_nist_csf2_profile,
)
from attestful.frameworks.hitrust import (
    HITRUST_CONTROLS,
    HITRUST_FRAMEWORK_ID,
    HITRUST_VERSION,
    HITRUSTControl,
    HITRUSTFramework,
    HITRUSTMaturityScore,
    CATEGORY_ISMP,
    CATEGORY_ACCESS_CONTROL,
    CATEGORY_HR_SECURITY,
    CATEGORY_RISK_MANAGEMENT,
    CATEGORY_SECURITY_POLICY,
    CATEGORY_ORG_SECURITY,
    CATEGORY_COMPLIANCE,
    CATEGORY_ASSET_MANAGEMENT,
    CATEGORY_PHYSICAL_SECURITY,
    CATEGORY_OPERATIONS,
    CATEGORY_SDLC,
    CATEGORY_INCIDENT_MANAGEMENT,
    CATEGORY_BCM,
    CATEGORY_PRIVACY,
    MATURITY_POLICY,
    MATURITY_PROCEDURE,
    MATURITY_IMPLEMENTED,
    MATURITY_MEASURED,
    MATURITY_MANAGED,
    create_hitrust_evaluator,
    get_hitrust_aws_checks,
    get_hitrust_framework,
    get_controls_by_category,
    get_hipaa_mapped_controls,
    get_control_count_by_category,
)

__all__ = [
    # SOC 2
    "SOC2_CONTROLS",
    "SOC2_FRAMEWORK_ID",
    "SOC2_VERSION",
    "SOC2Control",
    "SOC2Framework",
    "TSC_AVAILABILITY",
    "TSC_CONFIDENTIALITY",
    "TSC_PRIVACY",
    "TSC_PROCESSING_INTEGRITY",
    "TSC_SECURITY",
    "create_soc2_evaluator",
    "get_soc2_aws_checks",
    "get_soc2_azure_checks",
    "get_soc2_gcp_checks",
    "get_soc2_framework",
    # NIST 800-53
    "NIST_800_53_CONTROLS",
    "NIST_800_53_FRAMEWORK_ID",
    "NIST_800_53_VERSION",
    "NIST80053Control",
    "NIST80053Framework",
    "FEDRAMP_LOW",
    "FEDRAMP_MODERATE",
    "FEDRAMP_HIGH",
    "create_nist_800_53_evaluator",
    "get_nist_800_53_aws_checks",
    "get_nist_800_53_framework",
    "get_fedramp_baseline_controls",
    # ISO 27001
    "ISO_27001_CONTROLS",
    "ISO_27001_FRAMEWORK_ID",
    "ISO_27001_VERSION",
    "ISO27001Control",
    "ISO27001Framework",
    "DOMAIN_ORGANIZATIONAL",
    "DOMAIN_PEOPLE",
    "DOMAIN_PHYSICAL",
    "DOMAIN_TECHNOLOGICAL",
    "create_iso_27001_evaluator",
    "get_iso_27001_aws_checks",
    "get_iso_27001_framework",
    "get_controls_by_domain",
    "get_control_count_by_domain",
    # HITRUST
    "HITRUST_CONTROLS",
    "HITRUST_FRAMEWORK_ID",
    "HITRUST_VERSION",
    "HITRUSTControl",
    "HITRUSTFramework",
    "HITRUSTMaturityScore",
    "CATEGORY_ISMP",
    "CATEGORY_ACCESS_CONTROL",
    "CATEGORY_HR_SECURITY",
    "CATEGORY_RISK_MANAGEMENT",
    "CATEGORY_SECURITY_POLICY",
    "CATEGORY_ORG_SECURITY",
    "CATEGORY_COMPLIANCE",
    "CATEGORY_ASSET_MANAGEMENT",
    "CATEGORY_PHYSICAL_SECURITY",
    "CATEGORY_OPERATIONS",
    "CATEGORY_SDLC",
    "CATEGORY_INCIDENT_MANAGEMENT",
    "CATEGORY_BCM",
    "CATEGORY_PRIVACY",
    "MATURITY_POLICY",
    "MATURITY_PROCEDURE",
    "MATURITY_IMPLEMENTED",
    "MATURITY_MEASURED",
    "MATURITY_MANAGED",
    "create_hitrust_evaluator",
    "get_hitrust_aws_checks",
    "get_hitrust_framework",
    "get_controls_by_category",
    "get_hipaa_mapped_controls",
    "get_control_count_by_category",
    # NIST CSF 2.0
    "MaturityCriteria",
    "NistCategory",
    "NistFunction",
    "NistSubcategory",
    "get_all_categories",
    "get_all_functions",
    "get_all_subcategories",
    "get_category",
    "get_function",
    "get_subcategory",
    "ControlMappingResult",
    "EvidenceMapping",
    "MappingEngine",
    "MappingLogic",
    "MappingStatus",
    "EntityType",
    "MaturityBreakdown",
    "NistCSFMaturityCalculator",
    "MaturityConfig",
    "NistCSFMaturityScore",
    "NistCSF2OSCALConverter",
    "NistCSF2ProfileGenerator",
    "create_nist_csf2_catalog",
    "create_nist_csf2_profile",
    "ensure_csf2_catalog_exists",
    "ensure_csf2_profiles_exist",
    "get_csf2_catalog_path",
    "get_csf2_profile_path",
    "save_nist_csf2_catalog",
    "save_nist_csf2_profile",
]
