"""
OSCAL (Open Security Controls Assessment Language) implementation.

This module provides Pydantic models and utilities for working with OSCAL
documents including catalogs, profiles, components, SSPs, and assessments.
"""

from attestful.oscal.models import (
    # Common
    OSCALDocument,
    Metadata,
    Property,
    Link,
    ResponsibleParty,
    Party,
    Role,
    BackMatter,
    Resource,
    # Catalog
    Catalog,
    Group,
    Control,
    Parameter,
    Part,
    # Profile
    Profile,
    Import,
    Merge,
    Modify,
    # Component
    ComponentDefinition,
    Component,
    ControlImplementation,
    ImplementedRequirement,
    # SSP
    SystemSecurityPlan,
    SystemCharacteristics,
    SystemImplementation,
    SSPControlImplementation,
    SSPImplementedRequirement,
    SystemComponent,
    SystemUser,
    SystemId,
    SystemStatus,
    ImportProfile,
    AuthorizationBoundary,
    ByComponent,
    # Assessment
    AssessmentResults,
    Result,
    Finding,
    Observation,
    # POA&M
    PlanOfActionAndMilestones,
    PoamItem,
    Milestone,
    Response,
    Risk,
    ImportSSP,
    PoamLocalDefinitions,
)
from attestful.oscal.ssp import (
    SSPDiff,
    SSPDiffResult,
    SSPDifference,
    SSPGenerator,
    SSPLoader,
    SSPValidationIssue,
    SSPValidationResult,
    SSPValidator,
    SystemConfig,
    ComponentConfig,
    UserConfig,
    create_ssp_from_scan_results,
)
from attestful.oscal.assessment import (
    AssessmentComparison,
    AssessmentHistoryTracker,
    AssessmentResultsGenerator,
    AssessmentResultsLoader,
    AssessmentConfig,
    AssessmentSnapshot,
    ComplianceTrajectory,
    MaturityScoreMapper,
    MaturityScoreMappingConfig,
    POAMConfig,
    POAMGenerator,
    RemediationTask,
    ScanResultMapper,
    ScanResultMappingConfig,
    TrendData,
    create_assessment_from_scan,
    create_poam_from_findings,
    get_assessment_summary,
)
from attestful.oscal.catalog import (
    CatalogIndex,
    CatalogLoader,
    resolve_parameters,
)
from attestful.oscal.profile import (
    ProfileLoader,
    ProfileResolver,
    ResolvedCatalog,
    create_profile,
    get_profile_summary,
)
from attestful.oscal.component import (
    ComponentDefinitionGenerator,
    ComponentDefinitionIndex,
    ComponentDefinitionLoader,
    ComponentConfig,
    ComponentRegistry,
    ControlImplementationConfig,
    create_aws_component_definition,
    create_azure_component_definition,
    create_component_from_check_results,
    get_component_definition_summary,
    merge_component_definitions,
)

__all__ = [
    # Common
    "OSCALDocument",
    "Metadata",
    "Property",
    "Link",
    "ResponsibleParty",
    "Party",
    "Role",
    "BackMatter",
    "Resource",
    # Catalog
    "Catalog",
    "Group",
    "Control",
    "Parameter",
    "Part",
    # Profile
    "Profile",
    "Import",
    "Merge",
    "Modify",
    # Component
    "ComponentDefinition",
    "Component",
    "ControlImplementation",
    "ImplementedRequirement",
    # SSP
    "SystemSecurityPlan",
    "SystemCharacteristics",
    "SystemImplementation",
    "SSPControlImplementation",
    "SSPImplementedRequirement",
    "SystemComponent",
    "SystemUser",
    "SystemId",
    "SystemStatus",
    "ImportProfile",
    "AuthorizationBoundary",
    "ByComponent",
    # SSP Generator
    "SSPDiff",
    "SSPDiffResult",
    "SSPDifference",
    "SSPGenerator",
    "SSPLoader",
    "SSPValidationIssue",
    "SSPValidationResult",
    "SSPValidator",
    "SystemConfig",
    "ComponentConfig",
    "UserConfig",
    "create_ssp_from_scan_results",
    # Assessment
    "AssessmentResults",
    "Result",
    "Finding",
    "Observation",
    # POA&M
    "PlanOfActionAndMilestones",
    "PoamItem",
    "Milestone",
    "Response",
    "Risk",
    "ImportSSP",
    "PoamLocalDefinitions",
    # Assessment Generator
    "AssessmentComparison",
    "AssessmentHistoryTracker",
    "AssessmentResultsGenerator",
    "AssessmentResultsLoader",
    "AssessmentConfig",
    "AssessmentSnapshot",
    "ComplianceTrajectory",
    "MaturityScoreMapper",
    "MaturityScoreMappingConfig",
    "POAMConfig",
    "POAMGenerator",
    "RemediationTask",
    "ScanResultMapper",
    "ScanResultMappingConfig",
    "TrendData",
    "create_assessment_from_scan",
    "create_poam_from_findings",
    "get_assessment_summary",
    # Catalog
    "CatalogIndex",
    "CatalogLoader",
    "resolve_parameters",
    # Profile
    "ProfileLoader",
    "ProfileResolver",
    "ResolvedCatalog",
    "create_profile",
    "get_profile_summary",
    # Component
    "ComponentDefinitionGenerator",
    "ComponentDefinitionIndex",
    "ComponentDefinitionLoader",
    "ComponentConfig",
    "ComponentRegistry",
    "ControlImplementationConfig",
    "create_aws_component_definition",
    "create_azure_component_definition",
    "create_component_from_check_results",
    "get_component_definition_summary",
    "merge_component_definitions",
]
