apiVersion: v1
kind: Service
metadata:
  name: {{ include "attestful.fullname" . }}
  labels:
    {{- include "attestful.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if .Values.api.enabled }}
    - port: {{ .Values.service.apiPort }}
      targetPort: api
      protocol: TCP
      name: api
    {{- end }}
    {{- if .Values.dashboard.enabled }}
    - port: {{ .Values.service.dashboardPort }}
      targetPort: dashboard
      protocol: TCP
      name: dashboard
    {{- end }}
    {{- if .Values.metrics.enabled }}
    - port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "attestful.selectorLabels" . | nindent 4 }}
